variables:
  DOCKER_IMAGE_TAG: $CI_PIPELINE_IID
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG

stages:
  - build
  - deploy

build:image:dev:
  stage: build
  tags:
    - shell-main-pc
  rules:
    - if: $CI_COMMIT_REF_NAME == "dev" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: on_success
    - when: never
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .

deploy:image:dev:
  stage: deploy
  tags:
    - shell-main-pc
  variables:
    PROJ: sam-train-backend
  rules:
    - if: $CI_COMMIT_REF_NAME == "dev" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: on_success
    - when: never
  before_script:
    - echo $USER
    - echo $PROJ
  script:
    - docker stop $PROJ || echo $?
    - docker rm $PROJ || echo $?
    - docker run -d --name=$PROJ -p 8555:5000 --restart=always --env-file $ENV_FILE $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
